package com.servidorcentral.enums;

public enum Country {

	AFGANISTAN("Afganistán", "AF"),
	ALBANIA("Albania", "AL"),
	ALEMANIA("Alemania", "DE"),
	ANDORRA("Andorra", "AD"),
	ANGOLA("Angola", "AO"),
	ANGUILA("Anguila", "AI"),
	ANTIGUA_BARBUDA("Antigua y Barbuda", "AG"),
	ANTILLAS_NEERLANDESAS("Antillas Neerlandesas", "AN"),
	ANTARTIDA("Antártida", "AQ"),
	ARABIA_SAUDITA("Arabia Saudita", "SA"),
	ARGELIA("Argelia", "DZ"),
	ARGENTINA("Argentina", "AR"),
	ARMENIA("Armenia", "AM"),
	ARUBA("Aruba", "AW"),
	AUSTRALIA("Australia", "AU"),
	AUSTRIA("Austria", "AT"),
	AZERBAYAN("Azerbayán", "AZ"),
	BAHAMAS("Bahamas", "BS"),
	BAHREIN("Bahrein", "BH"),
	BANGLADESH("Bangladesh", "BD"),
	BARBADOS("Barbados", "BB"),
	BELICE("Belice", "BZ"),
	BENIN("Benín", "BJ"),
	BHUTAN("Bhután", "BT"),
	BIELORRUSIA("Bielorrusia", "BY"),
	BIRMANIA("Birmania", "MM"),
	BOLIVIA("Bolivia", "BO"),
	BOSNIA_HERZEGOVINA("Bosnia y Herzegovina", "BA"),
	BOTSUANA("Botsuana", "BW"),
	BRASIL("Brasil", "BR"),
	BRUNEI("Brunéi", "BN"),
	BULGARIA("Bulgaria", "BG"),
	BURKINA_FASO("Burkina Faso", "BF"),
	BURUNDI("Burundi", "BI"),
	BELGICA("Bélgica", "BE"),
	CABO_VERDE("Cabo Verde", "CV"),
	CAMBOYA("Camboya", "KH"),
	CAMERUN("Camerún", "CM"),
	CANADA("Canadá", "CA"),
	CHAD("Chad", "TD"),
	CHILE("Chile", "CL"),
	CHINA("China", "CN"),
	CHIPRE("Chipre", "CY"),
	CIUDAD_VATICANO("Ciudad del Vaticano", "VA"),
	COLOMBIA("Colombia", "CO"),
	COMORAS("Comoras", "KM"),
	CONGO("Congo", "CG"),
	COREA_NORTE("Corea del Norte", "KP"),
	COREA_SUR("Corea del Sur", "KR"),
	COSTA_RICA("Costa Rica", "CR"),
	COSTA_MARFIL("Costa de Marfil", "CI"),
	CROACIA("Croacia", "HR"),
	CUBA("Cuba", "CU"),
	DINAMARCA("Dinamarca", "DK"),
	DOMINICA("Dominica", "DM"),
	ECUADOR("Ecuador", "EC"),
	EGIPTO("Egipto", "EG"),
	EL_SALVADOR("El Salvador", "SV"),
	EMIRATOS_ARABES_UNIDOS("Emiratos Árabes Unidos", "AE"),
	ERITREA("Eritrea", "ER"),
	ESLOVAQUIA("Eslovaquia", "SK"),
	ESLOVENIA("Eslovenia", "SI"),
	ESPANA("España", "ES"),
	ESTADOS_UNIDOS_AMERICA("Estados Unidos de América", "US"),
	ESTONIA("Estonia", "EE"),
	ETIOPIA("Etiopía", "ET"),
	FILIPINAS("Filipinas", "PH"),
	FINLANDIA("Finlandia", "FI"),
	FIYI("Fiyi", "FJ"),
	FRANCIA("Francia", "FR"),
	GABON("Gabón", "GA"),
	GAMBIA("Gambia", "GM"),
	GEORGIA("Georgia", "GE"),
	GHANA("Ghana", "GH"),
	GIBRALTAR("Gibraltar", "GI"),
	GRANADA("Granada", "GD"),
	GRECIA("Grecia", "GR"),
	GROENLANDIA("Groenlandia", "GL"),
	GUADALUPE("Guadalupe", "GP"),
	GUAM("Guam", "GU"),
	GUATEMALA("Guatemala", "GT"),
	GUAYANA_FRANCESA("Guayana Francesa", "GF"),
	GUERNSEY("Guernsey", "GG"),
	GUINEA("Guinea", "GN"),
	GUINEA_ECUATORIAL("Guinea Ecuatorial", "GQ"),
	GUINEA_BISSAU("Guinea-Bissau", "GW"),
	GUYANA("Guyana", "GY"),
	HAITI("Haití", "HT"),
	HONDURAS("Honduras", "HN"),
	HUNGRIA("Hungría", "HU"),
	INDIA("India", "IN"),
	INDONESIA("Indonesia", "ID"),
	IRAK("Irak", "IQ"),
	IRLANDA("Irlanda", "IE"),
	IRAN("Irán", "IR"),
	ISLA_BOUVET("Isla Bouvet", "BV"),
	ISLA_NORFOLK("Isla Norfolk", "NF"),
	ISLA_MAN("Isla de Man", "IM"),
	ISLA_NAVIDAD("Isla de Navidad", "CX"),
	ISLANDIA("Islandia", "IS"),
	ISLAS_BERMUDAS("Islas Bermudas", "BM"),
	ISLAS_CAIMAN("Islas Caimán", "KY"),
	ISLAS_COCOS("Islas Cocos (Keeling)", "CC"),
	ISLAS_COOK("Islas Cook", "CK"),
	ISLAS_FEROE("Islas Feroe", "FO"),
	ISLAS_GEROGIAS_SANDWICH("Islas Georgias del Sur y Sandwich del Sur", "GS"),
	ISLAS_HEARD_MCDONALD("Islas Heard y McDonald", "HM"),
	ISLAS_MALVINAS("Islas Malvinas", "FK"),
	ISLAS_MARIANAS_NORTE("Islas Marianas del Norte", "MP"),
	ISLAS_MARSHALL("Islas Marshall", "MH"),
	ISLAS_PITCAIRN("Islas Pitcairn", "PN"),
	ISLAS_SALOMON("Islas Salomón", "SB"),
	ISLAS_TURCAS_CAICOS("Islas Turcas y Caicos", "TC"),
	ISLAS_ULTRAMARINAS_MENORES_USA("Islas Ultramarinas Menores de Estados Unidos", "UM"),
	ISLAS_VIRGENES_BRITANICAS("Islas Vírgenes Británicas", "VG"),
	ISLAS_VIRGENES_USA("Islas Vírgenes de los Estados Unidos", "VI"),
	ISLAS_ALAND("Islas de Åland", "AX"),
	ISRAEL("Israel", "IL"),
	ITALIA("Italia", "IT"),
	JAMAICA("Jamaica", "JM"),
	JAPON("Japón", "JP"),
	JERSEY("Jersey", "JE"),
	JORDANIA("Jordania", "JO"),
	KAZAJISTAN("Kazajistán", "KZ"),
	KENIA("Kenia", "KE"),
	KIRGIZSTAN("Kirgizstán", "KG"),
	KIRIBATI("Kiribati", "KI"),
	KUWAIT("Kuwait", "KW"),
	LAOS("Laos", "LA"),
	LESOTO("Lesoto", "LS"),
	LETONIA("Letonia", "LV"),
	LIBERIA("Liberia", "LR"),
	LIBIA("Libia", "LY"),
	LIECHTENSTEIN("Liechtenstein", "LI"),
	LITUANIA("Lituania", "LT"),
	LUXEMBURGO("Luxemburgo", "LU"),
	LIBANO("Líbano", "LB"),
	MACEDONIA("Macedonia", "MK"),
	MADAGASCAR("Madagascar", "MG"),
	MALASIA("Malasia", "MY"),
	MALAWI("Malawi", "MW"),
	MALDIVAS("Maldivas", "MV"),
	MALI("Mali", "ML"),
	MALTA("Malta", "MT"),
	MARRUECOS("Marruecos", "MA"),
	MARTINICA("Martinica", "MQ"),
	MAURICIO("Mauricio", "MU"),
	MAURITANIA("Mauritania", "MR"),
	MAYOTTE("Mayotte", "YT"),
	MICRONESIA("Micronesia", "FM"),
	MOLDAVIA("Moldavia", "MD"),
	MONGOLIA("Mongolia", "MN"),
	MONTENEGRO("Montenegro", "ME"),
	MONTSERRAT("Montserrat", "MS"),
	MOZAMBIQUE("Mozambique", "MZ"),
	MEXICO("México", "MX"),
	MONACO("Mónaco", "MC"),
	NAMIBIA("Namibia", "NA"),
	NAURU("Nauru", "NR"),
	NEPAL("Nepal", "NP"),
	NICARAGUA("Nicaragua", "NI"),
	NIGER("Niger", "NE"),
	NIGERIA("Nigeria", "NG"),
	NIUE("Niue", "NU"),
	NORUEGA("Noruega", "NO"),
	NUEVA_CALEDONIA("Nueva Caledonia", "NC"),
	NUEVA_ZELANDA("Nueva Zelanda", "NZ"),
	OMAN("Omán", "OM"),
	PAKISTAN("Pakistán", "PK"),
	PALAU("Palau", "PW"),
	PALESTINA("Palestina", "PS"),
	PANAMA("Panamá", "PA"),
	PAPUA_NUEVA_GUINEA("Papúa Nueva Guinea", "PG"),
	PARAGUAY("Paraguay", "PY"),
	PAISES_BAJOS("Países Bajos", "NL"),
	PERU("Perú", "PE"),
	POLINESIA_FRANCESA("Polinesia Francesa", "PF"),
	POLONIA("Polonia", "PL"),
	PORTUGAL("Portugal", "PT"),
	PUERTO_RICO("Puerto Rico", "PR"),
	QATAR("Qatar", "QA"),
	REINO_UNIDO("Reino Unido", "GB"),
	REPUBLICA_CENTROAFRICANA("República Centroafricana", "CF"),
	REPUBLICA_CHECA("República Checa", "CZ"),
	REPUBLICA_DEMOCRATICA_CONGO("República Democrática del Congo", "CD"),
	REPUBLICA_DOMINICA("República Dominicana", "DO"),
	REPUBLICA_ARABE_SAHARAUI("República Árabe Saharaui Democrática", "EH"),
	REUNION("Reunión", "RE"),
	RUANDA("Ruanda", "RW"),
	RUMANIA("Rumanía", "RO"),
	RUSIA("Rusia", "RU"),
	SAMOA("Samoa", "WS"),
	SAMOA_AMERICANA("Samoa Americana", "AS"),
	SAN_BARTOLOME("San Bartolomé", "BL"),
	SAN_CRISTOBAL_NIEVES("San Cristóbal y Nieves", "KN"),
	SAN_MARINO("San Marino", "SM"),
	SAN_MARTIN("San Martín (Francia)", "MF"),
	SAN_PEDRO_MIQUELON("San Pedro y Miquelón", "PM"),
	SAN_VICENTE_GRANADINAS("San Vicente y las Granadinas", "VC"),
	SANTA_ELENA("Santa Elena", "SH"),
	SANTA_LUCIA("Santa Lucía", "LC"),
	SANTO_TOME_PRINCIPE("Santo Tomé y Príncipe", "ST"),
	SENEGAL("Senegal", "SN"),
	SERBIA("Serbia", "RS"),
	SEYCHELLES("Seychelles", "SC"),
	SIERRA_LEONA("Sierra Leona", "SL"),
	SINGAPUR("Singapur", "SG"),
	SIRIA("Siria", "SY"),
	SOMALIA("Somalia", "SO"),
	SRI_LANKA("Sri Lanka", "LK"),
	SUDAFRICA("Sudáfrica", "ZA"),
	SUDAN("Sudán", "SD"),
	SUECIA("Suecia", "SE"),
	SUIZA("Suiza", "CH"),
	SURINAM("Surinám", "SR"),
	SVALBARD_JAN_MAYEN("Svalbard y Jan Mayen", "SJ"),
	SWAZILANDIA("Swazilandia", "SZ"),
	TADJIKISTAN("Tadjikistán", "TJ"),
	TAILANDIA("Tailandia", "TH"),
	TAIWAN("Taiwán", "TW"),
	TANZANIA("Tanzania", "TZ"),
	TERRITORIO_BRITANICO_OCEANO_INDICO("Territorio Británico del Océano Índico", "IO"),
	TERRITORIOS_AUSTRALES_ANTARTICAS_FRANCESES("Territorios Australes y Antárticas Franceses", "TF"),
	TIMOR_ORIENTAL("Timor Oriental", "TL"),
	TOGO("Togo", "TG"),
	TOKELAU("Tokelau", "TK"),
	TONGA("Tonga", "TO"),
	TRINIDAD_TOBAGO("Trinidad y Tobago", "TT"),
	TUNEZ("Tunez", "TN"),
	TURKMENISTAN("Turkmenistán", "TM"),
	TURQUIA("Turquía", "TR"),
	TUVALU("Tuvalu", "TV"),
	UCRANIA("Ucrania", "UA"),
	UGANDA("Uganda", "UG"),
	URUGUAY("Uruguay", "UY"),
	UZBEKISTAN("Uzbekistán", "UZ"),
	VANUATU("Vanuatu", "VU"),
	VENEZUELA("Venezuela", "VE"),
	VIETNAM("Vietnam", "VN"),
	WALLIS_FUTUNA("Wallis y Futuna", "WF"),
	YEMEN("Yemen", "YE"),
	YIBUTI("Yibuti", "DJ"),
	ZAMBIA("Zambia", "ZM"),
	ZIMBABUE("Zimbabue", "ZW");

	private String name;
	private String code;

	Country() {}

    Country(String name) {
        this.name = name;
    }

	Country(String name, String code) {
		this.name = name;
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public String getCode() {
		return this.code;
	}

	public static String[] getValues() {
		String[] values = new String[Country.values().length];
		for (int i = 0; i < Country.values().length; i++) {
			values[i] = Country.values()[i].name;
		}
		return values;
	}

	public static Country fromString(String nameOrCode) {
		for (Country country : Country.values()) {
			if (country.getName().equalsIgnoreCase(nameOrCode)
					|| country.getCode().equals(nameOrCode)
					|| country.name().equals(nameOrCode)) {
				return country;
			}
		}
        throw new IllegalArgumentException("There is no country with the name entered: " + nameOrCode);
	}

}

